COMMAND_TYPE = "command_type"
CMD_COMMAND = "cmd_command"
CMD = "cmd"
SPEECH_OUTPUT = "speech_output"
SPEECH_TYPE = "speech_type"
SPEECH_LIST = "speech_list"
SPEECH_ARGS = "speech_args"
DIALOG = "dialog"
YES = "true"
NO = "false"
DYNAMIC = "dynamic"
STATIC = "static"
TIME_DELIMITER = "-:."
CMD_ARGS = "cmd_args"
SECOND_TO_NANO = 1e+9
OPEN_LINK = "openLink"
LINK = "link"
WIKIPEDIA = "wikipedia"
PHRASES = "phrases"
RANDOM = "random"
ARGS_SEP = "args_sep"
ADD_EACH = "add_each"
CONCAT = "concat"
AHK = "ahk"
AHK_PATH = "ahk_path"
PICK_FIRST_MATCH = "pick_first_match"
REGEX_ON = "regex_on"
PREFIX = "prefix"
POSTFIX = "postfix"
COMMAND_FOLDER = "command_folder"

### MACROS ###
IMG_MACRO = "img_macro"

IMG = "img"
POSITION = "position"

DEFINE = "define"
WAIT = "wait"
AIM = "aim"
CLICK = "click"

### ERROR CODES ###
ERROR = "error"
ERROR_CODE = "error_code"
