COMMAND_TYPE = "command_type"
CMD_COMMAND = "cmd_command"
CMD = "cmd"
SPEECH_OUTPUT = "speech_output"
SPEECH_TYPE = "speech_type"
SPEECH_LIST = "speech_list"
SPEECH_ARGS = "speech_args"
DIALOG = "dialog"
YES = "true"
NO = "false"
DYNAMIC = "dynamic"
STATIC = "static"
TIME_DELIMITER = "-:."
CMD_ARGS = "cmd_args"
SECOND_TO_NANO = 1e+9

ERROR = "error"
ERROR_CODE = "error_code"
