COMMAND_TYPE = "command_type"
CMD_COMMAND = "cmd_command"
CMD = "cmd"
SPEECH_OUTPUT = "speech_output"
SPEECH_TYPE = "speech_type"
SPEECH_LIST = "speech_list"
SPEECH_ARGS = "speech_args"
DIALOG = "dialog"
YES = "true"
NO = "false"
DYNAMIC = "dynamic"
STATIC = "static"
TIME_DELIMITER = "-:."
CMD_ARGS = "cmd_args"
SECOND_TO_NANO = 1e+9
OPEN_LINK = "openLink"
LINK = "link"
WIKIPEDIA = "wikipedia"
PHRASES = "phrases"
RANDOM = "random"
ARGS_SEP = "args_sep"
ADD_EACH = "add_each"
CONCAT = "concat"
AHK = "ahk"
AHK_PATH = "ahk_path"
PICK_FIRST_MATCH = "pick_first_match"
REGEX_ON = "regex_on"
PREFIX = "prefix"
POSTFIX = "postfix"
COMMAND_FOLDER = "command_folder"
PHRASE_VAR = "phrase_var"


### MACROS ###
IMG_MACRO = "img_macro"
CHECK_ALL_SCREENS = "check_all_screens"

STRAIGHT = "straight"
WATCH = "watch"

IMG = "img"
POSITION = "position"
SIZE = "size"
X = 0
Y = 1

CENTER = "center"
LEFT_TOP = "left_top"
RIGHT_TOP = "right_top"
LEFT_BOTTOM = "left_bottom"
RIGHT_BOTTOM = "right_bottom"
LEFT_CENTER = "left_center"
RIGHT_CENTER = "right_center"

DEFINE = "define"
TRIGGER = "trigger"
WAIT = "wait"
AIM = "aim"
POS = "pos"
MOVE = "move"
CLICK = "click"

### ERROR CODES ###
ERROR = "error"
ERROR_CODE = "error_code"
