io_devices:
  input_device:
    index: 0
    name: Default
  output_device:
    index: 5
    name: Default
models:
  wake_word:
    name: PicoVoice Porcupine
  intent:
    name: LUNA Speach-to-Intent (BETA)
